version: '3'
services:
  app:
    build: .
    container_name: weather_monitoring_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - API_KEY=your_openweathermap_api_key

  db:
    image: sqlite:latest
    container_name: weather_db
    volumes:
      - ./data:/var/lib/sqlite
